# config.py

# YM babie
API_KEY_A = 'PKEXHX8IJVK8962ZJNBC'
API_SECRET_A = 'GJhpPgQiaSGdfDy7OZWkUTUDNXfYJGUbdEXRFIpZ'

# Rahul Das
API_KEY_B = 'PK3AWIAOZEOXKW75WFAS'
API_SECRET_B = 'c9Ww7hLUGjjc4qRMa3yWSdAXAcgLrZpUEc97bM2K'